name: Build and deploy Node.js app to Azure Web App - vartikgptapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      env:
        CI: true
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # This is the key change
      
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8699B11DC34E40DFB1A48DA220EE6570 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17D4F7ADA8934D15BB633D3AB810B24A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5B594A7C7A7243EDA8F1B74000369C71 }}
        auth-type: 'SERVICE_PRINCIPAL'
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vartikgptapp'
        slot-name: 'Production'
        package: .
