name: Build and deploy Node.js app to Azure Web App - VartikGPT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      # If you have a production build step, include it here
      - name: Build the project for production
        run: |
          npm run build || echo "No build script found, skipping build."

      # Testing step (optional)
      - name: Run tests
        run: |
          npm run test || echo "No test script found, skipping tests."

      - name: Prepare artifact for deployment
        run: |
          mkdir -p deployment
          cp -r * deployment/
          zip -r release.zip deployment/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8699B11DC34E40DFB1A48DA220EE6570 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17D4F7ADA8934D15BB633D3AB810B24A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5B594A7C7A7243EDA8F1B74000369C71 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VartikGPT'
          slot-name: 'Production'
          package: './deployment'
