name: Build and deploy Node.js app to Azure Web App - vartikgptapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          npm run export --if-present

      - name: Compress files
        run: tar -czf node-app.tar.gz -C out .  # Change 'out' to '.next' if not using static export

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Extract files
        run: mkdir -p myapp && tar -xzf node-app.tar.gz -C myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55D185749504469ABBA2494EBE914C22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3728FC759A904E09B86CEFFBAD74EB46 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5EBB74ADC03B4898BC185E1EBA994FF2 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'vartikgptapp'
          slot-name: 'Production'
          package: myapp  # Changed from ./build to myapp
